set -g status-position top
set -g status-justify left
set -g status-style "bg=default,fg=#cdd6f4"

# Colors
# active_border = #8aadf4
# inactive_border = #24273A
# background = #1e1e2e
# foreground = #cdd6f4
# accent = #eba0ac

set -g status-left "#[fg=#8aadf4,bg=default,bold] #S #[fg=#585b70,nobold]| "
set -g status-left-length 200

set -g status-right "#[fg=#585b70,bg=default]  #{b:pane_current_path} #[fg=#8aadf4,bold]#[fg=#1e1e2e,bg=#8aadf4] 󱑒 %H:%M "
set -g status-right-length 200

set -g window-status-format "#[fg=#585b70,bg=default] #I #W "
set -g window-status-current-format "#[fg=#eba0ac,bg=default,bold] #I #W "

# Pane borders
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#8aadf4"

# Message style
set -g message-style "bg=#1e1e2e,fg=#cdd6f4"
set -g message-command-style "bg=#1e1e2e,fg=#cdd6f4"

# Mode style (selection)
set -g mode-style "bg=#45475a,fg=#cdd6f4"
