# Arch-Minimal WSL Configuration
# -----------------------------------------------------------------------------
format = """[](#7aa2f7)[󰣇 ](bg:#7aa2f7 fg:#1a1b26)[ ](fg:#7aa2f7)$directory$git_branch$git_status$character"""
right_format = """$python$nodejs$lua$golang$rust$cmd_duration"""

add_newline = true

[directory]
style = "italic fg:#bb9af7"
truncation_length = 3
truncation_symbol = "…/"
format = "[$path]($style) "

[character]
success_symbol = "[❯](bold #9ece6a)"
error_symbol = "[❯](bold #f7768e)"

[git_branch]
symbol = " "
style = "bold #7aa2f7"
format = "[$symbol$branch]($style) "

[git_status]
style = "fg:#f7768e"
format = "([$all_status$ahead_behind]($style) )"

[python]
symbol = " "
style = "bold #e0af68"
format = "[$symbol($version)]($style) "

[nodejs]
symbol = " "
style = "bold #9ece6a"
format = "[$symbol($version)]($style) "

[lua]
symbol = " "
style = "bold #7aa2f7"
format = "[$symbol($version)]($style) "

[cmd_duration]
min_time = 500
style = "fg:#565f89"
format = "[$duration]($style)"

[line_break]
disabled = true
